management:
  info:
    java:
      enabled: true
    os:
      enabled: true
  server:
    port: 9292
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"